# Generated by Django 5.2.4 on 2025-07-30 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_logininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldpassword', models.CharField(max_length=15)),
                ('newpassword', models.CharField(max_length=15)),
                ('confirmpassword', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='logininfo',
            old_name='Password',
            new_name='password',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='profiles')),
                ('bio', models.TextField()),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.logininfo')),
            ],
        ),
    ]
